### ISSUE TITLE
The example from the docs doesn't work

### ISSUE THREAD

**Issue by tomkcook** [t184256/asyncio-loop-local#1]
Python 3.12.3
aiohttp 3.9.5
asyncio-loop-local 0.0.4

Test code:

```
import asyncio
import aiohttp
import asyncio_loop_local

ClientSession = asyncio_loop_local.sticky_singleton_acm(aiohttp.ClientSession)

async def amain():
    url = "http://localhost:5984/"
    async with ClientSession(url) as session:
        async with session.get("/info/1234") as resp:
            print(f"Got response: {await resp.text()}")

    async with ClientSession(url) as session:
        async with session.get("/info/1234") as resp:
            print(f"Got response: {await resp.text()}")

asyncio.run(amain())
```

Result:

```
Got response: {"_id":"1234","_rev":"1-JRfA6koQdf/354NdU9ht2NkU+Iw="}
Traceback (most recent call last):
  File "/home/tkcook/Scratch/veeadb/test.py", line 17, in <module>
    asyncio.run(amain())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tkcook/Scratch/veeadb/test.py", line 14, in amain
    async with session.get("/info/1234") as resp:
  File "/home/tkcook/Scratch/veeadb/venv/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/tkcook/Scratch/veeadb/venv/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/home/tkcook/Scratch/veeadb/venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tkcook/Scratch/veeadb/venv/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

Note that, in this case, `http://localhost:5984/` is a CouchDB API-compatible server.

**Comment by tomkcook** [comment]
Sorry, nvm, this is the server not implementing keep-alive correctly.
